"""Parse bet365 football odds into a tidy CSV.

    python tools/bet365.py --har bet365.har     # THE WORKING PATH
    python tools/bet365.py --limit 2 --verbose  # live fetch — does not currently work

Writes outputs/bet365_odds.csv — one row per selection, with decimal odds.

USE THE HAR PATH. Capture one in the browser (DevTools > Network > save as HAR while
clicking through the fixtures you want) and parse it here. It is reliable, needs no
VPN, and cannot break when bet365 redeploy.

The live fetch is kept because the discovery walk and parser are correct and it may
start working, but as of 2026-08-16 every content API call returns 200 with zero bytes
while the same call from a browser succeeds. Ruled out along the way: Cloudflare TLS
fingerprinting (curl_cffi impersonation passes; the homepage returns a full 42KB shell),
geography (a HAR captured at the same location succeeds), session state (11 real cookies
plus the X-Net-Sync-Term header, still empty), and compression (zero RAW bytes, so
nothing arrived at all). Needs `pip install curl_cffi`.

Note bet365's terms prohibit automated access, so treat this as an occasional manual
supplement — never a dependency of the weekly pipeline.

--- their wire format ---
Records split on '|', fields on ';', then KEY=VALUE. Record types that matter:
    EV  an event: a competition or a fixture, with NA (name) and PD (its id)
    MG  market group, e.g. "Full Time Result", "Player to Score or Assist"
    MA  a column within that group
    PA  a selection, OD = FRACTIONAL odds

Simple markets are one MA holding PAs that each carry a name and odds. Player markets
are a COLUMN-MAJOR GRID: the first MA lists player names with no odds, later MAs are odds
columns, and rows align by position across columns. Both shapes are handled below.
"""
import argparse
import json
import os
import sys
import time
import uuid

import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from fpl_pipeline import config  # noqa: E402

BASE = "https://www.bet365.com"
IMPERSONATE = "chrome131"
# The UK football node, from the captured session. '#ABM#' is the navigation form of a
# node; the '#AC#' form identifies the thing itself.
UK_FOOTBALL = "#ABM#B1#C1#D1002#E91422157#G40#"
HEADERS = {"Accept": "*/*", "Referer": BASE + "/", "Accept-Language": "en-US,en;q=0.9",
           "Sec-Fetch-Dest": "empty", "Sec-Fetch-Mode": "cors", "Sec-Fetch-Site": "same-origin"}


def _ungzip(raw):
    import gzip
    return gzip.decompress(raw)


def _unbrotli(raw):
    import brotli
    return brotli.decompress(raw)


def _unzstd(raw):
    import zstandard
    return zstandard.ZstdDecompressor().decompress(raw)


def to_decimal(frac):
    """bet365 quotes fractions: '13/2' -> 7.5, 'EVS' -> 2.0."""
    if not frac:
        return None
    frac = frac.strip()
    if frac.upper() in ("EVS", "EVENS"):
        return 2.0
    if "/" not in frac:
        try:
            return float(frac)
        except ValueError:
            return None
    num, _, den = frac.partition("/")
    try:
        return round(1 + float(num) / float(den), 4)
    except (ValueError, ZeroDivisionError):
        return None


def parse_wire(body):
    """Their delimited payload -> list of dicts, in document order."""
    records = []
    for chunk in body.split("|"):
        if not chunk:
            continue
        parts = chunk.split(";")
        rec = {"_type": parts[0]}
        for field in parts[1:]:
            if "=" in field:
                key, value = field.split("=", 1)
                rec[key] = value
        records.append(rec)
    return records


class Bet365:
    def __init__(self, impersonate=IMPERSONATE, delay=1.5, verbose=False, session_har=None):
        from curl_cffi import requests as creq
        self.session = creq.Session(impersonate=impersonate)
        self.session.headers.update(HEADERS)
        self.delay = delay
        self.verbose = verbose
        self.last = (None, 0)
        home = self.session.get(BASE + "/", timeout=30)   # pick up cookies like a browser
        if verbose:
            print(f"    homepage -> {home.status_code}, {len(home.text)} chars, "
                  f"{len(self.session.cookies)} cookies")

        # Borrow a real browser session. The homepage alone yields ~2 cookies while a
        # live browser holds ~11 (aps03, pstk, swt, ...) plus an X-Net-Sync-Term header
        # generated by their obfuscated bundle. If the content APIs need that state,
        # this is the only way to supply it without running their JavaScript.
        if session_har:
            har = json.load(open(session_har, encoding="utf-8"))
            entry = next((e for e in har["log"]["entries"]
                          if "contentapi" in e["request"]["url"]), None)
            if not entry:
                raise SystemExit(f"no contentapi request found in {session_har}")
            for c in entry["request"]["cookies"]:
                self.session.cookies.set(c["name"], c["value"], domain=".bet365.com")

            # Replicate the captured request EXACTLY rather than hand-assembling headers.
            # Order matters to HTTP/2 fingerprinting, and we were previously omitting
            # X-Request-Id, which the browser sends on every content API call.
            self.session.headers.clear()
            for h in entry["request"]["headers"]:
                name = h["name"]
                if name.startswith(":") or name.lower() in ("cookie", "host", "content-length"):
                    continue
                self.session.headers[name] = h["value"]
            token = "X-Net-Sync-Term" in self.session.headers
            print(f"    replicated {len(self.session.headers)} browser headers"
                  f"{' incl. sync token' if token else ''} + "
                  f"{len(entry['request']['cookies'])} cookies from {session_har}")
            if verbose:
                print(f"      header order: {', '.join(list(self.session.headers)[:9])}")

    def get(self, path, pd):
        time.sleep(self.delay)                        # be a considerate client
        # The browser mints a fresh correlation id per call; a replayed one may be
        # treated as a duplicate and answered with nothing.
        if "X-Request-Id" in self.session.headers:
            self.session.headers["X-Request-Id"] = str(uuid.uuid4())
        r = self.session.get(f"{BASE}/{path}", params={"lid": 1, "zid": 3, "pd": pd,
                                                       "cid": 169, "cgid": 1, "ctid": 169},
                             timeout=30)
        body = r.text or ""
        raw = r.content or b""
        self.last = (r.status_code, len(body))
        if r.status_code != 200:
            raise SystemExit(f"{path} returned {r.status_code}")
        if self.verbose:
            print(f"    {path} pd={pd[:34]}... -> {r.status_code}, "
                  f"{len(body)} chars / {len(raw)} raw bytes"
                  f", encoding={r.headers.get('content-encoding', '-')}")
        # Bytes arrived but decoded to nothing: the server used a compression the client
        # advertised but cannot actually decode (zstd/br). Decode it explicitly.
        if raw and not body:
            enc = (r.headers.get("content-encoding") or "").lower()
            for name, decode in (("zstd", _unzstd), ("br", _unbrotli), ("gzip", _ungzip)):
                if name in enc or not enc:
                    try:
                        body = decode(raw).decode("utf-8", "replace")
                        if body:
                            if self.verbose:
                                print(f"      recovered {len(body)} chars via {name}")
                            break
                    except Exception:
                        continue
            self.last = (r.status_code, len(body))
        return parse_wire(body)

    def competitions(self):
        records = self.get("splashcontentapi/changecompetition", UK_FOOTBALL)
        found = {r["NA"]: r["PD"] for r in records
                 if r["_type"] == "EV" and r.get("NA") and r.get("PD")}
        if not found:
            status, size = self.last
            print(f"\n  discovery returned {status} with {size} chars")
            if size == 0:
                print("  EMPTY BODY (200, zero bytes). The live fetch does not work; use"
                      "\n  --har instead. Investigated 2026-08-16 and RULED OUT:"
                      "\n    * Cloudflare fingerprinting — homepage returns a full 42KB shell"
                      "\n    * geography — a browser HAR captured in the same place succeeds"
                      "\n    * session state — 11 real cookies + X-Net-Sync-Term, still empty"
                      "\n    * compression — zero RAW bytes, so nothing arrived to decode"
                      "\n  Whatever differs is in how the browser frames the request (HTTP/2"
                      "\n  fingerprint, header order, or state set up by earlier calls) and"
                      "\n  would need real reverse-engineering to find.")
            else:
                kinds = {}
                for r in records:
                    kinds[r["_type"]] = kinds.get(r["_type"], 0) + 1
                print(f"  body parsed but held no competitions; record types: {kinds}")
                print("  -> the node id in UK_FOOTBALL is probably stale; recapture a HAR")
        return found

    def fixtures(self, competition_pd):
        """Fixtures in a competition. changefixture returns a node's siblings, so the
        navigation ('#ABM#') form of the competition id is what it wants."""
        for pd in (competition_pd.replace("#AC#", "#ABM#", 1), competition_pd):
            records = self.get("splashcontentapi/changefixture", pd)
            found = {r["NA"]: r["PD"] for r in records
                     if r["_type"] == "EV" and " v " in r.get("NA", "") and r.get("PD")}
            if found:
                return found
        return {}

    def odds(self, fixture_pd):
        return self.get("matchbettingcontentapi/coupon", fixture_pd)


def parse_coupon(records, fixture):
    """Selections from one fixture's coupon, handling both market shapes."""
    rows, group, blocks = [], None, []

    def flush():
        """Emit the finished market group."""
        if not blocks:
            return
        # A names column carries PA names but no odds; if present, this is a grid.
        names = next((pas for _, pas in blocks
                      if pas and all(p.get("NA") and not p.get("OD") for p in pas)), None)
        for header, pas in blocks:
            if pas is names:
                continue
            for i, pa in enumerate(pas):
                decimal = to_decimal(pa.get("OD"))
                if decimal is None:
                    continue
                if names and i < len(names):
                    selection, column = names[i].get("NA", ""), header
                else:
                    selection, column = pa.get("NA", ""), header
                rows.append({"fixture": fixture, "market_group": group,
                             "market": column, "selection": selection,
                             "handicap": pa.get("HA", ""), "odds_fractional": pa.get("OD"),
                             "odds_decimal": decimal})

    for rec in records:
        kind = rec["_type"]
        if kind == "MG":
            flush()
            group, blocks = rec.get("NA", ""), []
        elif kind == "MA":
            blocks.append((rec.get("NA", ""), []))
        elif kind == "PA" and blocks:
            blocks[-1][1].append(rec)
    flush()
    return rows


def from_har(path):
    """Parse a saved HAR — the no-network path, and how this format was reverse-engineered."""
    har = json.load(open(path, encoding="utf-8"))
    rows = []
    for entry in har["log"]["entries"]:
        if "matchbettingcontentapi/coupon" not in entry["request"]["url"]:
            continue
        body = entry["response"]["content"].get("text") or ""
        records = parse_wire(body)
        name = next((r.get("NA") for r in records if r["_type"] == "EV" and r.get("NA")), "unknown")
        rows += parse_coupon(records, name)
    return rows


def replay(session_har, impersonate=IMPERSONATE, http_version=None, prime=False):
    """Re-fetch every URL the browser called, and compare live size to captured size.

    The decisive diagnostic: each of these demonstrably returned data in the browser a
    few minutes ago, so whatever still works live is usable, and whatever does not
    isolates the difference. Also the fastest way to see whether it is ONE endpoint
    misbehaving or all of them.
    """
    from curl_cffi import requests as creq
    har = json.load(open(session_har, encoding="utf-8"))
    entries = har["log"]["entries"]

    kwargs = {"impersonate": impersonate}
    if http_version:
        kwargs["http_version"] = http_version
    session = creq.Session(**kwargs)

    seed = next((e for e in entries if "contentapi" in e["request"]["url"]), entries[0])
    session.headers.clear()
    for h in seed["request"]["headers"]:
        if not h["name"].startswith(":") and h["name"].lower() not in (
                "cookie", "host", "content-length"):
            session.headers[h["name"]] = h["value"]
    for c in seed["request"]["cookies"]:
        session.cookies.set(c["name"], c["value"], domain=".bet365.com")

    session.get(BASE + "/", timeout=30)
    if prime:
        # The browser loaded these app bundles before any content call; the server may
        # only regard a session as initialised once it has served them.
        for e in entries:
            if "/Api/1/Blob" in e["request"]["url"]:
                r = session.get(e["request"]["url"], timeout=30)
                print(f"  primed Blob -> {r.status_code}, {len(r.content)} bytes")
                time.sleep(1)

    print(f"\n{'endpoint':<42}{'captured':>10}{'live':>10}  match")
    print("-" * 74)
    for e in entries:
        url = e["request"]["url"]
        if "contentapi" not in url:
            continue
        captured = len(e["response"]["content"].get("text") or "")
        if "X-Request-Id" in session.headers:
            session.headers["X-Request-Id"] = str(uuid.uuid4())
        time.sleep(1.5)
        r = session.get(url, timeout=30)
        live = len(r.content or b"")
        path = url.split("bet365.com/")[-1].split("?")[0]
        flag = "YES" if live > 0 else "empty"
        print(f"{path:<42}{captured:>10}{live:>10}  {flag}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--competition", default="England Premier League")
    ap.add_argument("--har", help="parse this HAR instead of fetching")
    ap.add_argument("--limit", type=int, help="only this many fixtures (for a quick test)")
    ap.add_argument("--verbose", action="store_true", help="show every call's status and size")
    ap.add_argument("--session-har", help="reuse cookies + sync token from a FRESH capture")
    ap.add_argument("--replay", help="re-fetch every URL in this HAR and compare sizes")
    ap.add_argument("--http1", action="store_true", help="force HTTP/1.1 instead of HTTP/2")
    ap.add_argument("--prime", action="store_true", help="fetch the app bundles first")
    args = ap.parse_args()

    if args.replay:
        replay(args.replay, http_version="v1" if args.http1 else None, prime=args.prime)
        sys.exit()

    if args.har:
        rows = from_har(args.har)
        print(f"parsed {len(rows)} selections from {args.har}")
    else:
        client = Bet365(verbose=args.verbose, session_har=args.session_har)
        comps = client.competitions()
        print(f"{len(comps)} competitions found")
        if not comps:
            sys.exit("discovery failed — see the diagnosis above")
        if args.competition not in comps:
            print("available:", ", ".join(sorted(comps)[:20]))
            sys.exit(f"'{args.competition}' not among them")

        fixtures = client.fixtures(comps[args.competition])
        print(f"{len(fixtures)} fixtures in {args.competition}")
        if not fixtures:
            sys.exit("no fixtures discovered — the navigation id form may have changed")

        rows = []
        for i, (name, pd) in enumerate(list(fixtures.items())[:args.limit], 1):
            got = parse_coupon(client.odds(pd), name)
            rows += got
            print(f"  [{i}/{len(fixtures)}] {name:<34} {len(got):>4} selections")

    if not rows:
        sys.exit("no odds parsed")
    df = pd.DataFrame(rows)
    out = os.path.join(config.OUTPUTS_DIR, "bet365_odds.csv")
    df.to_csv(out, index=False)
    print(f"\n{len(df)} selections across {df['fixture'].nunique()} fixtures "
          f"and {df['market_group'].nunique()} market groups -> {os.path.relpath(out, config.ROOT)}")
    print("\nmarket groups:", ", ".join(sorted(df["market_group"].unique())[:12]))
